<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup Label="UI">
    <PackageVersion Include="Microsoft.AspNetCore.Components.Web" Version="10.0.12" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebView.Wpf" Version="10.0.110" />
  </ItemGroup>

  <ItemGroup Label="Hosting">
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageVersion Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageVersion Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup Label="Oracle">
    <PackageVersion Include="Oracle.ManagedDataAccess.Core" Version="23.26.301" />
  </ItemGroup>

  <ItemGroup Label="Tests">
    <PackageVersion Include="NSubstitute" Version="6.2.0" />
    <PackageVersion Include="Testcontainers.Oracle" Version="4.15.0" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>

</Project>
