using System.Diagnostics;
using FerretSharp.Core.Connections;
using FerretSharp.Core.Data;
using FerretSharp.Core.Oracle;
using FerretSharp.Core.Query;
using FerretSharp.Core.Schema;
using Oracle.ManagedDataAccess.Client;

namespace FerretSharp.Integration.Tests;

/// <summary>Editing (WP-09): flush, commit, rollback, undo, conflicts – with two workspace sessions like the app.</summary>
public sealed class EditingTests(OracleContainerFixture oracle) : IAsyncLifetime
{
    private static readonly SemaphoreSlim Gate = new(1, 1);
    private static bool _created;

    private static CancellationToken Ct => TestContext.Current.CancellationToken;

    private string Owner => oracle.RequireProfile().Profile.EffectiveSchema;

    public async ValueTask InitializeAsync()
    {
        await Gate.WaitAsync(Ct);
        try
        {
            if (_created)
            {
                return;
            }

            await using var connection = new OracleConnection(oracle.RequireConnectionString());
            await connection.OpenAsync(Ct);
            foreach (var sql in new[]
            {
                """
                CREATE TABLE ED_TYPES (
                    ID     NUMBER(10) PRIMARY KEY,
                    TXT    VARCHAR2(20 CHAR),
                    NTXT   NVARCHAR2(10),
                    KZ     CHAR(3),
                    BETRAG NUMBER(12,2),
                    GROSS  NUMBER(38),
                    DATUM  DATE,
                    TS     TIMESTAMP(6),
                    DATEN  RAW(8),
                    DEF    VARCHAR2(10) DEFAULT 'std',
                    LFD    NUMBER GENERATED BY DEFAULT AS IDENTITY,
                    MENGE  NUMBER CONSTRAINT CK_ED_MENGE CHECK (MENGE >= 0)) SEGMENT CREATION IMMEDIATE
                """,
                "CREATE TABLE ED_NOKEY (TXT VARCHAR2(20), N NUMBER) SEGMENT CREATION IMMEDIATE",
                "INSERT INTO ED_NOKEY VALUES ('eins', 1)",
                "INSERT INTO ED_NOKEY VALUES ('zwei', 2)",
            })
            {
                await using var command = connection.CreateCommand();
                command.CommandText = sql;
                await command.ExecuteNonQueryAsync(Ct);
            }

            _created = true;
        }
        finally
        {
            Gate.Release();
        }
    }

    public ValueTask DisposeAsync() => ValueTask.CompletedTask;

    private async Task<IDatabaseConnection> OpenAsync(string action)
    {
        var (profile, password) = oracle.RequireProfile();
        return await new OracleDatabaseConnector().OpenAsync(profile, password, action, Ct);
    }

    private async Task ExecuteAsync(string sql)
    {
        await using var connection = new OracleConnection(oracle.RequireConnectionString());
        await connection.OpenAsync(Ct);
        await using var command = connection.CreateCommand();
        command.CommandText = sql;
        await command.ExecuteNonQueryAsync(Ct);
    }

    private Task<TableDetails> DetailsAsync(IDatabaseConnection connection, string table) =>
        connection.Schema.GetDetailsAsync(new TableSummary(Owner, table, TableKind.Table), Ct);

    private static async Task<RowData?> RowAsync(IDatabaseConnection connection, TableDetails table, int id)
    {
        var page = await connection.Data.ReadPageAsync(table, [FilterCondition.Of("ID", FilterOperator.Equals, id.ToString())], [], new PageSpec(0, 10), Ct);
        return page.Rows.SingleOrDefault();
    }

    private static int I(TableDetails table, string column) => table.Columns.ToList().FindIndex(c => c.Name == column);

    private static async Task<FlushBatch> FlushAsync(IDatabaseConnection connection, ChangeTracker tracker, FlushOptions? options = null)
    {
        var operations = tracker.PendingOperations();
        var result = await connection.Editor.FlushAsync(tracker.Table, operations, options ?? new FlushOptions(), Ct);
        return tracker.MarkFlushed(operations, result.NewKeys);
    }

    [Fact]
    public async Task Insert_update_delete_round_trip_for_all_editable_types()
    {
        await using var a = await OpenAsync("Edit A");
        await using var check = await OpenAsync("Edit check");
        var table = await DetailsAsync(a, "ED_TYPES");
        var tracker = new ChangeTracker(table);

        var row = tracker.AddRow();
        foreach (var (column, text) in new[]
        {
            ("ID", "100"), ("TXT", "Grüße & 50%_"), ("NTXT", "Ωμέγα"), ("KZ", "AB"), ("BETRAG", "1.234,56"),
            ("GROSS", "12345678901234567890"), ("DATUM", "05.10.2026 14:30:15"), ("TS", "05.10.2026 14:30:15.123456"), ("DATEN", "CAFE01"),
        })
        {
            Assert.True(tracker.SetValue(row, I(table, column), text).IsValid, column);
        }

        var operations = tracker.PendingOperations();
        var result = await a.Editor.FlushAsync(table, operations, new FlushOptions(), Ct);
        tracker.MarkFlushed(operations, result.NewKeys);
        var stored = result.InsertedRows[row.Id];
        Assert.Equal(new RowKey.PrimaryKey([100m]), stored.Key);
        Assert.Equal("std", stored.Values[I(table, "DEF")]); // default applied: column left out of the INSERT
        Assert.NotNull(stored.Values[I(table, "LFD")]); // identity value
        Assert.Equal(TransactionMode.ReadWrite, a.Editor.Transaction.Mode);
        Assert.Null(await RowAsync(check, table, 100)); // not committed

        await a.Editor.CommitAsync(Ct);
        Assert.Equal(TransactionMode.None, a.Editor.Transaction.Mode);
        var committed = (await RowAsync(check, table, 100))!;
        Assert.Equal("Grüße & 50%_", committed.Values[I(table, "TXT")]);
        Assert.Equal("Ωμέγα", committed.Values[I(table, "NTXT")]);
        Assert.Equal("AB ", committed.Values[I(table, "KZ")]); // CHAR is blank-padded
        Assert.Equal(1234.56m, committed.Values[I(table, "BETRAG")]);
        Assert.Equal(12345678901234567890m, committed.Values[I(table, "GROSS")]);
        Assert.Equal(new DateTime(2026, 10, 5, 14, 30, 15), committed.Values[I(table, "DATUM")]);
        Assert.Equal(new DateTime(2026, 10, 5, 14, 30, 15).AddTicks(1234560), committed.Values[I(table, "TS")]);
        Assert.Equal([0xCA, 0xFE, 0x01], (byte[])committed.Values[I(table, "DATEN")]!);

        tracker.Clear();
        Assert.True(tracker.SetValue(committed, I(table, "BETRAG"), "").IsValid);
        Assert.True(tracker.SetValue(committed, I(table, "KZ"), "XYZ").IsValid);
        await FlushAsync(a, tracker);
        await a.Editor.CommitAsync(Ct);
        var updated = (await RowAsync(check, table, 100))!;
        Assert.Null(updated.Values[I(table, "BETRAG")]);
        Assert.Equal("XYZ", updated.Values[I(table, "KZ")]);

        tracker.Clear();
        tracker.Delete(updated);
        await FlushAsync(a, tracker);
        await a.Editor.CommitAsync(Ct);
        Assert.Null(await RowAsync(check, table, 100));
    }

    [Fact]
    public async Task Flushed_changes_are_invisible_to_another_workspace_until_commit()
    {
        await ExecuteAsync("INSERT INTO ED_TYPES (ID, TXT) VALUES (200, 'alt')");
        await using var a = await OpenAsync("Workspace A");
        await using var b = await OpenAsync("Workspace B");
        var table = await DetailsAsync(a, "ED_TYPES");
        var tracker = new ChangeTracker(table);

        tracker.SetValue((await RowAsync(a, table, 200))!, I(table, "TXT"), "neu");
        await FlushAsync(a, tracker);

        Assert.Equal("neu", (await RowAsync(a, table, 200))!.Values[I(table, "TXT")]); // A sees its own change
        Assert.Equal("alt", (await RowAsync(b, table, 200))!.Values[I(table, "TXT")]); // B does not

        await a.Editor.CommitAsync(Ct);
        Assert.Equal("neu", (await RowAsync(b, table, 200))!.Values[I(table, "TXT")]);
    }

    /// <summary>WP-09 is done when this holds: a lock conflict between two workspaces shows up after the wait, not never.</summary>
    [Fact]
    public async Task Lock_conflict_between_workspaces_is_reported_after_the_wait()
    {
        await ExecuteAsync("INSERT INTO ED_TYPES (ID, TXT, MENGE) VALUES (300, 'gesperrt', 1)");
        await using var a = await OpenAsync("Workspace A");
        await using var b = await OpenAsync("Workspace B");
        var table = await DetailsAsync(a, "ED_TYPES");
        var trackerA = new ChangeTracker(table);
        var trackerB = new ChangeTracker(table);
        trackerA.SetValue((await RowAsync(a, table, 300))!, I(table, "TXT"), "von A");
        trackerB.SetValue((await RowAsync(b, table, 300))!, I(table, "MENGE"), "2");
        await FlushAsync(a, trackerA); // A holds the row lock now

        var stopwatch = Stopwatch.StartNew();
        var error = await Assert.ThrowsAsync<LockConflictException>(() => FlushAsync(b, trackerB, new FlushOptions(LockWaitSeconds: 2)));
        stopwatch.Stop();

        // Oracle 23 answers an expired WAIT with ORA-00054 ("… or timeout expired"); older versions with ORA-30006.
        Assert.Contains(error.Error.ErrorCode, new[] { "ORA-00054", "ORA-30006" });
        Assert.InRange(stopwatch.Elapsed, TimeSpan.FromSeconds(1.5), TimeSpan.FromSeconds(6));
        Assert.Equal(1, trackerB.PendingCount); // still pending, nothing half written

        await a.Editor.CommitAsync(Ct);
        await FlushAsync(b, trackerB); // other column than A: no concurrency conflict
        await b.Editor.CommitAsync(Ct);
        await using var check = await OpenAsync("Edit check");
        var row = (await RowAsync(check, table, 300))!;
        Assert.Equal(("von A", 2m), (row.Values[I(table, "TXT")], row.Values[I(table, "MENGE")]));
    }

    [Fact]
    public async Task Lock_holders_name_the_workspace_that_holds_the_lock()
    {
        await GrantCatalogRoleAsync();
        await ExecuteAsync("INSERT INTO ED_TYPES (ID, TXT) VALUES (350, 'x')");
        await using var a = await OpenAsync("Bug 3711");
        await using var explorer = await OpenAsync("Explorer");
        var table = await DetailsAsync(a, "ED_TYPES");
        var tracker = new ChangeTracker(table);
        tracker.SetValue((await RowAsync(a, table, 350))!, I(table, "TXT"), "y");
        await FlushAsync(a, tracker);

        var holders = await explorer.Schema.GetLockHoldersAsync(table.Table.Ref, Ct);

        Assert.NotNull(holders);
        Assert.Contains(holders, h => h.Module == "FerretSharp" && h.Action == "Bug 3711");
        await a.Editor.RollbackAsync(Ct);
    }

    [Fact]
    public async Task Concurrent_change_of_the_same_column_is_a_conflict_unless_overwritten()
    {
        await ExecuteAsync("INSERT INTO ED_TYPES (ID, BETRAG, TXT) VALUES (400, 10, 'a')");
        await using var a = await OpenAsync("Workspace A");
        var table = await DetailsAsync(a, "ED_TYPES");
        var tracker = new ChangeTracker(table);
        tracker.SetValue((await RowAsync(a, table, 400))!, I(table, "BETRAG"), "12");
        await ExecuteAsync("UPDATE ED_TYPES SET BETRAG = 11, TXT = 'b' WHERE ID = 400"); // someone else, committed

        var conflict = await Assert.ThrowsAsync<ConcurrencyConflictException>(() => FlushAsync(a, tracker));
        var difference = Assert.Single(conflict.Differences); // TXT changed too, but A does not change it
        Assert.Equal((I(table, "BETRAG"), 10m, 11m), (difference.Column, difference.Expected, difference.Actual));

        await FlushAsync(a, tracker, new FlushOptions(Overwrite: new HashSet<Guid> { conflict.Operation.Change.Id }));
        await a.Editor.CommitAsync(Ct);
        Assert.Equal(12m, (await RowAsync(a, table, 400))!.Values[I(table, "BETRAG")]);
    }

    [Fact]
    public async Task Row_deleted_meanwhile_is_reported()
    {
        await ExecuteAsync("INSERT INTO ED_TYPES (ID, TXT) VALUES (500, 'x')");
        await using var a = await OpenAsync("Workspace A");
        var table = await DetailsAsync(a, "ED_TYPES");
        var tracker = new ChangeTracker(table);
        tracker.SetValue((await RowAsync(a, table, 500))!, I(table, "TXT"), "y");
        await ExecuteAsync("DELETE FROM ED_TYPES WHERE ID = 500");

        await Assert.ThrowsAsync<RowGoneException>(() => FlushAsync(a, tracker));
    }

    [Fact]
    public async Task A_failing_statement_rolls_back_the_whole_flush()
    {
        await ExecuteAsync("INSERT INTO ED_TYPES (ID, TXT, MENGE) VALUES (600, 'bleibt', 1)");
        await using var a = await OpenAsync("Workspace A");
        var table = await DetailsAsync(a, "ED_TYPES");
        var tracker = new ChangeTracker(table);
        tracker.SetValue((await RowAsync(a, table, 600))!, I(table, "TXT"), "geändert");
        var duplicate = tracker.AddRow();
        tracker.SetValue(duplicate, I(table, "ID"), "600");

        var error = await Assert.ThrowsAsync<WriteFailedException>(() => FlushAsync(a, tracker));

        Assert.Equal("ORA-00001", error.Error.ErrorCode);
        Assert.StartsWith("Eindeutigkeit verletzt", error.Message);
        Assert.Same(duplicate, error.Operation.Change);
        Assert.Equal("bleibt", (await RowAsync(a, table, 600))!.Values[I(table, "TXT")]); // the update before it is undone too
        Assert.Empty(a.Editor.Actions);

        tracker.Delete(duplicate);
        var check = (await RowAsync(a, table, 600))!;
        tracker.SetValue(check, I(table, "MENGE"), "5");
        tracker.Revert(check.Key);
        tracker.SetValue(check, I(table, "MENGE"), "-1");
        var constraint = await Assert.ThrowsAsync<WriteFailedException>(() => FlushAsync(a, tracker));
        Assert.Equal("ORA-02290", constraint.Error.ErrorCode);
        await a.Editor.RollbackAsync(Ct);
    }

    [Fact]
    public async Task Undo_takes_back_the_last_flush_only_and_rollback_everything()
    {
        await ExecuteAsync("INSERT INTO ED_TYPES (ID, TXT) VALUES (700, 'a')");
        await ExecuteAsync("INSERT INTO ED_TYPES (ID, TXT) VALUES (701, 'a')");
        await using var a = await OpenAsync("Workspace A");
        var table = await DetailsAsync(a, "ED_TYPES");
        var tracker = new ChangeTracker(table);

        tracker.SetValue((await RowAsync(a, table, 700))!, I(table, "TXT"), "erster");
        await FlushAsync(a, tracker);
        tracker.SetValue((await RowAsync(a, table, 701))!, I(table, "TXT"), "zweiter");
        var second = await FlushAsync(a, tracker);
        Assert.Equal(2, a.Editor.Actions.Count);

        Assert.Equal(WriteActionKind.Grid, (await a.Editor.UndoLastAsync(Ct))?.Kind);
        tracker.UndoFlush(second);

        Assert.Equal("erster", (await RowAsync(a, table, 700))!.Values[I(table, "TXT")]);
        Assert.Equal("a", (await RowAsync(a, table, 701))!.Values[I(table, "TXT")]);
        Assert.Equal(1, tracker.PendingCount); // the undone change is pending again

        await a.Editor.RollbackAsync(Ct);
        Assert.Equal(TransactionMode.None, a.Editor.Transaction.Mode);
        Assert.Equal("a", (await RowAsync(a, table, 700))!.Values[I(table, "TXT")]);
    }

    /// <summary>
    /// Grid writes and SQL statements share the transaction: a rollback to the grid's savepoint would take the later
    /// statement along. Undo therefore always takes back the newest action, whoever wrote it.
    /// </summary>
    [Fact]
    public async Task Undo_takes_back_the_newest_action_also_a_statement_after_a_grid_write()
    {
        await ExecuteAsync("INSERT INTO ED_TYPES (ID, TXT) VALUES (710, 'a')");
        await ExecuteAsync("INSERT INTO ED_TYPES (ID, TXT) VALUES (711, 'a')");
        await using var a = await OpenAsync("Workspace A");
        var table = await DetailsAsync(a, "ED_TYPES");
        var tracker = new ChangeTracker(table);

        tracker.SetValue((await RowAsync(a, table, 710))!, I(table, "TXT"), "grid");
        await FlushAsync(a, tracker);
        var statement = await a.Editor.ExecuteAsync(new QuerySpec("UPDATE ED_TYPES SET TXT = 'sql' WHERE ID = 711", []), Ct);

        Assert.Equal(
            [(WriteActionKind.Grid, "ED_TYPES: 1 geändert", 1), (WriteActionKind.Statement, "UPDATE ED_TYPES", 1)],
            a.Editor.Actions.Select(x => (x.Kind, x.Description, x.Rows)));

        Assert.Equal(statement.Id, (await a.Editor.UndoLastAsync(Ct))?.Id); // the statement, not the older grid write
        Assert.Equal("grid", (await RowAsync(a, table, 710))!.Values[I(table, "TXT")]);
        Assert.Equal("a", (await RowAsync(a, table, 711))!.Values[I(table, "TXT")]);

        Assert.Equal(WriteActionKind.Grid, (await a.Editor.UndoLastAsync(Ct))?.Kind);
        Assert.Equal("a", (await RowAsync(a, table, 710))!.Values[I(table, "TXT")]);
        Assert.Empty(a.Editor.Actions);
        Assert.Null(await a.Editor.UndoLastAsync(Ct));

        await a.Editor.RollbackAsync(Ct);
        Assert.Empty(a.Editor.Actions);
    }

    [Fact]
    public async Task Tables_without_primary_key_are_edited_by_rowid()
    {
        await using var a = await OpenAsync("Workspace A");
        var table = await DetailsAsync(a, "ED_NOKEY");
        var rows = (await a.Data.ReadPageAsync(table, [], [new SortSpec("N", false)], new PageSpec(0, 10), Ct)).Rows;
        Assert.All(rows, r => Assert.IsType<RowKey.RowId>(r.Key));
        var tracker = new ChangeTracker(table);

        tracker.SetValue(rows[0], I(table, "TXT"), "EINS");
        tracker.Delete(rows[1]);
        await FlushAsync(a, tracker);

        var after = (await a.Data.ReadPageAsync(table, [], [new SortSpec("N", false)], new PageSpec(0, 10), Ct)).Rows;
        Assert.Equal(["EINS"], after.Select(r => r.Values[0]));
        await a.Editor.RollbackAsync(Ct);
    }

    [Fact]
    public async Task A_locked_session_cannot_flush()
    {
        await using var a = await OpenAsync("Prod");
        await a.UseReadOnlySnapshotsAsync(Ct);
        var table = await DetailsAsync(a, "ED_TYPES");
        var tracker = new ChangeTracker(table);
        tracker.SetValue(tracker.AddRow(), I(table, "ID"), "800");

        await Assert.ThrowsAsync<InvalidOperationException>(() => FlushAsync(a, tracker));
    }

    /// <summary>As SYSTEM (same password as the app user in the gvenzl image); new sessions get the role.</summary>
    private async Task GrantCatalogRoleAsync()
    {
        var system = new OracleConnectionStringBuilder(oracle.RequireConnectionString()) { UserID = "system" };
        await using var connection = new OracleConnection(system.ConnectionString);
        try
        {
            await connection.OpenAsync(Ct);
        }
        catch (OracleException ex)
        {
            Assert.Skip($"SYSTEM login not possible: {ex.Message}");
        }

        await using var command = connection.CreateCommand();
        command.CommandText = $"GRANT SELECT_CATALOG_ROLE TO {OracleIdentifier.Quote(Owner)}";
        await command.ExecuteNonQueryAsync(Ct);
    }
}
