-- FerretSharp sample schema: tables, views, a materialized view, quoted identifiers, composite keys, an IOT and
-- about 30 small master data tables (letter index). Run as the application user, see New-SampleDb.ps1.
SET FEEDBACK OFF
SET DEFINE OFF
WHENEVER SQLERROR EXIT FAILURE

CREATE TABLE KUNDEN (
    KUNDE_ID    NUMBER(10) CONSTRAINT PK_KUNDEN PRIMARY KEY,
    NAME        VARCHAR2(100 CHAR) NOT NULL,
    KUERZEL     CHAR(3 BYTE),
    ERSTELLT_AM DATE DEFAULT SYSDATE NOT NULL,
    UMSATZ      NUMBER(12,2),
    ANZAHL      INTEGER,
    CONSTRAINT UK_KUNDEN_KUERZEL UNIQUE (KUERZEL));

CREATE TABLE AUFTRAG (
    AUFTRAG_ID NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT PK_AUFTRAG PRIMARY KEY,
    KUNDE_ID   NUMBER(10) NOT NULL CONSTRAINT FK_AUFTRAG_KUNDE REFERENCES KUNDEN,
    STATUS     VARCHAR2(20 CHAR) DEFAULT 'OFFEN' NOT NULL,
    NOTIZ      CLOB);

CREATE TABLE AUFTRAG_POSITION (
    AUFTRAG_ID NUMBER NOT NULL CONSTRAINT FK_POS_AUFTRAG REFERENCES AUFTRAG,
    POS_NR     NUMBER(4) NOT NULL,
    MENGE      NUMBER,
    CONSTRAINT PK_AUFTRAG_POSITION PRIMARY KEY (AUFTRAG_ID, POS_NR));

CREATE TABLE LIEFERUNG (
    LIEFERUNG_ID NUMBER PRIMARY KEY,
    POS_NR       NUMBER(4),
    AUFTRAG_ID   NUMBER,
    CONSTRAINT FK_LIEF_POS FOREIGN KEY (AUFTRAG_ID, POS_NR) REFERENCES AUFTRAG_POSITION (AUFTRAG_ID, POS_NR));

CREATE TABLE RECHNUNG (
    RECHNUNG_ID NUMBER(12) PRIMARY KEY,
    AUFTRAG_ID  NUMBER CONSTRAINT FK_RECHNUNG_AUFTRAG REFERENCES AUFTRAG,
    KUNDE_ID    NUMBER(10) CONSTRAINT FK_RECHNUNG_KUNDE REFERENCES KUNDEN,
    BETRAG      NUMBER(12,2) NOT NULL,
    FAELLIG_AM  DATE,
    GEDRUCKT_AM TIMESTAMP(6));

CREATE TABLE "MixedCase" ("Id" NUMBER CONSTRAINT "Pk_Mixed" PRIMARY KEY, "Wert" NVARCHAR2(20), "raw col" RAW(16));
CREATE TABLE "notizen" (ID NUMBER PRIMARY KEY, TEXT VARCHAR2(4000));
CREATE TABLE LAND_IOT (CODE VARCHAR2(2) PRIMARY KEY, NAME VARCHAR2(50)) ORGANIZATION INDEX OVERFLOW;

CREATE VIEW V_KUNDEN_AUFTRAEGE AS
SELECT k.KUNDE_ID, k.NAME, COUNT(a.AUFTRAG_ID) AS ANZAHL
  FROM KUNDEN k LEFT JOIN AUFTRAG a ON a.KUNDE_ID = k.KUNDE_ID
 GROUP BY k.KUNDE_ID, k.NAME;

CREATE MATERIALIZED VIEW MV_UMSATZ AS SELECT KUNDE_ID, SUM(UMSATZ) AS SUMME FROM KUNDEN GROUP BY KUNDE_ID;

BEGIN
  FOR n IN (SELECT column_value AS name FROM TABLE(sys.odcivarchar2list(
      'ADRESSE','AKTE','ANSPRECHPARTNER','ARTIKEL','BANK','BELEG','BENUTZER','BESTELLUNG','BUCHUNG','DOKUMENT',
      'EINSTELLUNG','FILIALE','GUTSCHRIFT','HERSTELLER','KATEGORIE','KONTAKT','KONTO','LAGER','LAGERORT',
      'LIEFERANT','MAHNUNG','MANDANT','MITARBEITER','PREISLISTE','PRODUKT','PROJEKT','ROLLE','SPRACHE',
      'STEUERSATZ','TERMIN','VERSAND','WAEHRUNG','ZAHLUNG','ZAHLUNGSART'))) LOOP
    EXECUTE IMMEDIATE 'CREATE TABLE ' || n.name || ' (ID NUMBER(10) PRIMARY KEY, BEZEICHNUNG VARCHAR2(100 CHAR) NOT NULL, '
      || 'AKTIV NUMBER(1) DEFAULT 1 NOT NULL, ERSTELLT_AM DATE DEFAULT SYSDATE, GEAENDERT_AM TIMESTAMP(6))';
  END LOOP;
END;
/

ALTER TABLE ARTIKEL ADD (HERSTELLER_ID NUMBER(10) CONSTRAINT FK_ARTIKEL_HERSTELLER REFERENCES HERSTELLER, KATEGORIE_ID NUMBER(10) CONSTRAINT FK_ARTIKEL_KATEGORIE REFERENCES KATEGORIE);
ALTER TABLE KUNDEN ADD (ADRESSE_ID NUMBER(10) CONSTRAINT FK_KUNDEN_ADRESSE REFERENCES ADRESSE);
ALTER TABLE AUFTRAG_POSITION ADD (ARTIKEL_ID NUMBER(10) CONSTRAINT FK_POS_ARTIKEL REFERENCES ARTIKEL);

CREATE VIEW V_OFFENE_POSTEN AS SELECT r.RECHNUNG_ID, r.BETRAG, r.FAELLIG_AM FROM RECHNUNG r WHERE r.FAELLIG_AM < SYSDATE;

-- Lands in the recycle bin, which the explorer must not show.
CREATE TABLE WEG_DAMIT (ID NUMBER);
DROP TABLE WEG_DAMIT;

SELECT COUNT(*) AS OBJEKTE FROM user_objects WHERE object_type IN ('TABLE', 'VIEW', 'MATERIALIZED VIEW');
EXIT
