-- Sample data: 150,000 customers (with umlauts, "&", "%" and "_" in names, NULLs), 50,000 orders (some CLOBs).
SET FEEDBACK OFF
SET DEFINE OFF
WHENEVER SQLERROR EXIT FAILURE

INSERT INTO ADRESSE (ID, BEZEICHNUNG) SELECT LEVEL, 'Adresse ' || LEVEL FROM DUAL CONNECT BY LEVEL <= 1000;

INSERT INTO KUNDEN (KUNDE_ID, NAME, KUERZEL, ERSTELLT_AM, UMSATZ, ANZAHL, ADRESSE_ID)
SELECT LEVEL,
       CASE MOD(LEVEL, 13) WHEN 0 THEN 'Müller GmbH' WHEN 1 THEN 'Schmidt & Söhne' WHEN 2 THEN '50%_Rabatt AG' ELSE 'Kunde ' || LEVEL END,
       CASE WHEN LEVEL <= 500 THEN TO_CHAR(LEVEL, 'FM000') END,
       DATE '2015-01-01' + MOD(LEVEL * 37, 4000) + MOD(LEVEL, 24) / 24,
       CASE WHEN MOD(LEVEL, 7) = 0 THEN NULL ELSE ROUND(MOD(LEVEL * 7919, 25000000) / 100, 2) END,
       MOD(LEVEL, 50),
       MOD(LEVEL, 1000) + 1
  FROM DUAL CONNECT BY LEVEL <= 150000;

INSERT INTO AUFTRAG (KUNDE_ID, STATUS, NOTIZ)
SELECT MOD(LEVEL * 7, 150000) + 1,
       CASE MOD(LEVEL, 4) WHEN 0 THEN 'OFFEN' WHEN 1 THEN 'VERSANDT' WHEN 2 THEN 'STORNIERT' ELSE 'ABGESCHLOSSEN' END,
       CASE WHEN MOD(LEVEL, 50) = 0 THEN TO_CLOB('Lange Notiz ' || RPAD('-', 500, '-')) END
  FROM DUAL CONNECT BY LEVEL <= 50000;

COMMIT;
SELECT (SELECT COUNT(*) FROM KUNDEN) AS KUNDEN, (SELECT COUNT(*) FROM AUFTRAG) AS AUFTRAEGE FROM DUAL;
EXIT
