-- A wide table: VERTRAG with 71 columns and 20,000 rows (column search, horizontal scrolling, pinning).
SET FEEDBACK OFF
SET DEFINE OFF
WHENEVER SQLERROR EXIT FAILURE
CREATE TABLE VERTRAG (
  VERTRAG_ID NUMBER(10) CONSTRAINT PK_VERTRAG PRIMARY KEY,
  VERTRAGSNUMMER VARCHAR2(20 CHAR) NOT NULL, KUNDE_ID NUMBER(10) CONSTRAINT FK_VERTRAG_KUNDE REFERENCES KUNDEN,
  MANDANT_ID NUMBER(10) CONSTRAINT FK_VERTRAG_MANDANT REFERENCES MANDANT, VERTRAGSART VARCHAR2(20 CHAR), STATUS VARCHAR2(20 CHAR),
  BEZEICHNUNG VARCHAR2(200 CHAR), BESCHREIBUNG VARCHAR2(2000 CHAR), BEGINN_AM DATE, ENDE_AM DATE, KUENDIGUNG_AM DATE,
  KUENDIGUNGSFRIST_MONATE NUMBER(3), MINDESTLAUFZEIT_MONATE NUMBER(3), VERLAENGERUNG_MONATE NUMBER(3), AUTO_VERLAENGERUNG NUMBER(1),
  UNTERSCHRIEBEN_AM DATE, UNTERSCHRIEBEN_VON VARCHAR2(100 CHAR), GEGENGEZEICHNET_AM DATE, GEGENGEZEICHNET_VON VARCHAR2(100 CHAR),
  WAEHRUNG CHAR(3), NETTOBETRAG NUMBER(14,2), STEUERSATZ NUMBER(5,2), STEUERBETRAG NUMBER(14,2), BRUTTOBETRAG NUMBER(14,2),
  RABATT_PROZENT NUMBER(5,2), RABATT_BETRAG NUMBER(14,2), SKONTO_PROZENT NUMBER(5,2), SKONTO_TAGE NUMBER(3), ZAHLUNGSZIEL_TAGE NUMBER(3),
  ZAHLUNGSART VARCHAR2(20 CHAR), ZAHLUNGSRHYTHMUS VARCHAR2(20 CHAR), IBAN VARCHAR2(34 CHAR), BIC VARCHAR2(11 CHAR), KONTOINHABER VARCHAR2(100 CHAR),
  MANDATSREFERENZ VARCHAR2(35 CHAR), MANDAT_DATUM DATE, RECHNUNG_STRASSE VARCHAR2(100 CHAR), RECHNUNG_PLZ VARCHAR2(10 CHAR),
  RECHNUNG_ORT VARCHAR2(100 CHAR), RECHNUNG_LAND CHAR(2), LIEFER_STRASSE VARCHAR2(100 CHAR), LIEFER_PLZ VARCHAR2(10 CHAR),
  LIEFER_ORT VARCHAR2(100 CHAR), LIEFER_LAND CHAR(2), ANSPRECHPARTNER VARCHAR2(100 CHAR), ANSPRECHPARTNER_TELEFON VARCHAR2(30 CHAR),
  ANSPRECHPARTNER_EMAIL VARCHAR2(100 CHAR), VERTRIEBSMITARBEITER_ID NUMBER(10) CONSTRAINT FK_VERTRAG_VERTRIEB REFERENCES MITARBEITER,
  BETREUER_ID NUMBER(10) CONSTRAINT FK_VERTRAG_BETREUER REFERENCES MITARBEITER, PROJEKT_ID NUMBER(10) CONSTRAINT FK_VERTRAG_PROJEKT REFERENCES PROJEKT,
  KOSTENSTELLE VARCHAR2(20 CHAR), KOSTENTRAEGER VARCHAR2(20 CHAR), SACHKONTO VARCHAR2(20 CHAR), PREISLISTE_ID NUMBER(10) CONSTRAINT FK_VERTRAG_PREISLISTE REFERENCES PREISLISTE,
  INDEXIERUNG NUMBER(1), INDEX_BASISJAHR NUMBER(4), INDEX_SCHWELLE_PROZENT NUMBER(5,2), LETZTE_ANPASSUNG_AM DATE, NAECHSTE_ANPASSUNG_AM DATE,
  BONITAET VARCHAR2(10 CHAR), RISIKOKLASSE NUMBER(1), SICHERHEIT_BETRAG NUMBER(14,2), SICHERHEIT_ART VARCHAR2(30 CHAR),
  BEMERKUNG_INTERN VARCHAR2(4000 CHAR), BEMERKUNG_EXTERN VARCHAR2(4000 CHAR), EXTERNE_REFERENZ VARCHAR2(50 CHAR),
  ERSTELLT_AM TIMESTAMP(6), ERSTELLT_VON VARCHAR2(30 CHAR), GEAENDERT_AM TIMESTAMP(6), GEAENDERT_VON VARCHAR2(30 CHAR), VERSION NUMBER(10));
INSERT INTO MANDANT (ID, BEZEICHNUNG) SELECT LEVEL, 'Mandant ' || LEVEL FROM DUAL CONNECT BY LEVEL <= 3;
INSERT INTO MITARBEITER (ID, BEZEICHNUNG) SELECT LEVEL, 'Mitarbeiter ' || LEVEL FROM DUAL CONNECT BY LEVEL <= 40;
INSERT INTO PROJEKT (ID, BEZEICHNUNG) SELECT LEVEL, 'Projekt ' || LEVEL FROM DUAL CONNECT BY LEVEL <= 25;
INSERT INTO PREISLISTE (ID, BEZEICHNUNG) SELECT LEVEL, 'Preisliste ' || LEVEL FROM DUAL CONNECT BY LEVEL <= 5;
INSERT INTO VERTRAG
SELECT LEVEL, 'V-2026-' || LPAD(LEVEL, 6, '0'), MOD(LEVEL * 13, 150000) + 1, MOD(LEVEL, 3) + 1,
  CASE MOD(LEVEL, 3) WHEN 0 THEN 'WARTUNG' WHEN 1 THEN 'LIZENZ' ELSE 'SERVICE' END,
  CASE MOD(LEVEL, 5) WHEN 0 THEN 'GEKUENDIGT' ELSE 'AKTIV' END,
  'Vertrag ' || LEVEL, CASE WHEN MOD(LEVEL, 4) = 0 THEN 'Beschreibung zu Vertrag ' || LEVEL END,
  DATE '2020-01-01' + MOD(LEVEL * 7, 2000), DATE '2027-01-01' + MOD(LEVEL, 700), CASE WHEN MOD(LEVEL, 5) = 0 THEN DATE '2026-03-01' + MOD(LEVEL, 200) END,
  3, 12, 12, MOD(LEVEL, 2), DATE '2019-12-01' + MOD(LEVEL * 7, 2000), 'Unterzeichner ' || MOD(LEVEL, 30), DATE '2019-12-05' + MOD(LEVEL * 7, 2000), 'Gegenzeichner ' || MOD(LEVEL, 10),
  'EUR', ROUND(MOD(LEVEL * 7919, 1000000) / 100, 2), 19, ROUND(MOD(LEVEL * 7919, 1000000) / 100 * 0.19, 2), ROUND(MOD(LEVEL * 7919, 1000000) / 100 * 1.19, 2),
  MOD(LEVEL, 15), NULL, 2, 10, 30, CASE MOD(LEVEL, 2) WHEN 0 THEN 'LASTSCHRIFT' ELSE 'UEBERWEISUNG' END, 'MONATLICH',
  'DE' || LPAD(MOD(LEVEL * 104729, 1000000000), 20, '0'), 'COBADEFFXXX', 'Kunde ' || LEVEL, 'MREF-' || LEVEL, DATE '2020-01-01' + MOD(LEVEL, 900),
  'Hauptstrasse ' || MOD(LEVEL, 200), LPAD(MOD(LEVEL * 31, 99999), 5, '0'), 'Ort ' || MOD(LEVEL, 50), 'DE',
  CASE WHEN MOD(LEVEL, 3) = 0 THEN 'Lagerweg ' || MOD(LEVEL, 40) END, CASE WHEN MOD(LEVEL, 3) = 0 THEN LPAD(MOD(LEVEL * 17, 99999), 5, '0') END, CASE WHEN MOD(LEVEL, 3) = 0 THEN 'Lagerort ' || MOD(LEVEL, 9) END, CASE WHEN MOD(LEVEL, 3) = 0 THEN 'DE' END,
  'Ansprechpartner ' || LEVEL, '0221 ' || LEVEL, 'kontakt' || LEVEL || '@example.com', MOD(LEVEL, 40) + 1, MOD(LEVEL * 3, 40) + 1, MOD(LEVEL, 25) + 1,
  'KST-' || MOD(LEVEL, 12), 'KTR-' || MOD(LEVEL, 8), '8400', MOD(LEVEL, 5) + 1,
  MOD(LEVEL, 2), 2020, 5, DATE '2025-01-01' + MOD(LEVEL, 300), DATE '2027-01-01' + MOD(LEVEL, 300),
  CASE MOD(LEVEL, 3) WHEN 0 THEN 'A' WHEN 1 THEN 'B' ELSE 'C' END, MOD(LEVEL, 5) + 1, CASE WHEN MOD(LEVEL, 6) = 0 THEN 5000 END, CASE WHEN MOD(LEVEL, 6) = 0 THEN 'BUERGSCHAFT' END,
  CASE WHEN MOD(LEVEL, 10) = 0 THEN 'Interne Notiz ' || LEVEL END, NULL, 'EXT-' || LEVEL,
  SYSTIMESTAMP - NUMTODSINTERVAL(MOD(LEVEL, 1000), 'DAY'), 'import', SYSTIMESTAMP - NUMTODSINTERVAL(MOD(LEVEL, 100), 'DAY'), 'user' || MOD(LEVEL, 7), MOD(LEVEL, 9) + 1
FROM DUAL CONNECT BY LEVEL <= 20000;
COMMIT;
SELECT COUNT(*) AS SPALTEN FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'VERTRAG';
EXIT
