-- Material for the detail views: comments, check constraints (one disabled), indexes (function-based, descending),
-- a view on VERTRAG, an invalid view and optimizer statistics. Most FKs of VERTRAG stay without index on purpose.
SET FEEDBACK OFF
SET DEFINE OFF
WHENEVER SQLERROR EXIT FAILURE

COMMENT ON TABLE KUNDEN IS 'Kundenstamm: ein Eintrag je Kunde';
COMMENT ON COLUMN KUNDEN.KUERZEL IS 'Dreistelliges Kürzel, eindeutig';
COMMENT ON COLUMN KUNDEN.UMSATZ IS 'Jahresumsatz in EUR (netto)';
COMMENT ON TABLE VERTRAG IS 'Verträge mit Laufzeit, Zahlungs- und Indexierungsdaten';
COMMENT ON COLUMN VERTRAG.VERTRAGSNUMMER IS 'Fachliche Nummer im Format V-JJJJ-NNNNNN';
COMMENT ON COLUMN VERTRAG.KUENDIGUNGSFRIST_MONATE IS 'Frist zum Vertragsende in Monaten';
COMMENT ON COLUMN VERTRAG.STATUS IS 'AKTIV oder GEKUENDIGT';

ALTER TABLE VERTRAG ADD CONSTRAINT CK_VERTRAG_STATUS CHECK (STATUS IN ('AKTIV', 'GEKUENDIGT'));
ALTER TABLE VERTRAG ADD CONSTRAINT CK_VERTRAG_LAUFZEIT CHECK (ENDE_AM >= BEGINN_AM);
ALTER TABLE VERTRAG ADD CONSTRAINT CK_VERTRAG_RABATT CHECK (RABATT_PROZENT BETWEEN 0 AND 50) DISABLE;

CREATE INDEX IX_VERTRAG_KUNDE ON VERTRAG (KUNDE_ID);
CREATE INDEX IX_VERTRAG_NUMMER_UPPER ON VERTRAG (UPPER(VERTRAGSNUMMER));
CREATE INDEX IX_VERTRAG_ENDE ON VERTRAG (ENDE_AM DESC, STATUS);
CREATE INDEX IX_AUFTRAG_KUNDE ON AUFTRAG (KUNDE_ID);

CREATE VIEW V_VERTRAG_AKTIV AS
SELECT VERTRAG_ID, VERTRAGSNUMMER, KUNDE_ID, BEGINN_AM, ENDE_AM FROM VERTRAG WHERE STATUS = 'AKTIV';

-- Invalid view: its table loses the column afterwards.
CREATE TABLE ALT_IMPORT (ID NUMBER PRIMARY KEY, QUELLE VARCHAR2(20));
CREATE VIEW V_ALT_IMPORT AS SELECT ID, QUELLE FROM ALT_IMPORT;
ALTER TABLE ALT_IMPORT DROP COLUMN QUELLE;

EXEC DBMS_STATS.GATHER_SCHEMA_STATS(USER)

SELECT COUNT(*) AS UNGUELTIG FROM user_objects WHERE status = 'INVALID';
EXIT
