-- PL/SQL to look at (WP-28): packages with overloads and a body, a standalone procedure and function, a package body
-- that does not compile, a wrapped procedure, a large package and two triggers (one disabled).
SET FEEDBACK OFF
SET DEFINE OFF
WHENEVER SQLERROR EXIT FAILURE

CREATE OR REPLACE PACKAGE PKG_RECHNUNG AS
  -- Rechnungen erstellen und Beträge berechnen
  TYPE T_POSTEN IS RECORD (AUFTRAG_ID NUMBER, BETRAG NUMBER(12,2));
  C_MWST CONSTANT NUMBER := 0.19;

  FUNCTION BRUTTO(P_NETTO NUMBER) RETURN NUMBER;
  FUNCTION BRUTTO(P_NETTO NUMBER, P_SATZ NUMBER DEFAULT C_MWST) RETURN NUMBER;
  PROCEDURE ERSTELLE(P_AUFTRAG_ID IN NUMBER, P_RECHNUNG_ID OUT NUMBER, P_ZAEHLER IN OUT PLS_INTEGER);
  PROCEDURE OFFENE(P_KUNDE IN KUNDEN%ROWTYPE, P_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE AUFRAEUMEN;
END PKG_RECHNUNG;
/

CREATE OR REPLACE PACKAGE BODY PKG_RECHNUNG AS
  FUNCTION BRUTTO(P_NETTO NUMBER) RETURN NUMBER IS
  BEGIN
    RETURN ROUND(P_NETTO * (1 + C_MWST), 2);
  END;

  FUNCTION BRUTTO(P_NETTO NUMBER, P_SATZ NUMBER DEFAULT C_MWST) RETURN NUMBER IS
  BEGIN
    RETURN ROUND(P_NETTO * (1 + P_SATZ), 2);
  END;

  PROCEDURE ERSTELLE(P_AUFTRAG_ID IN NUMBER, P_RECHNUNG_ID OUT NUMBER, P_ZAEHLER IN OUT PLS_INTEGER) IS
    V_KUNDE_ID AUFTRAG.KUNDE_ID%TYPE;
  BEGIN
    SELECT KUNDE_ID INTO V_KUNDE_ID FROM AUFTRAG WHERE AUFTRAG_ID = P_AUFTRAG_ID;
    SELECT NVL(MAX(RECHNUNG_ID), 0) + 1 INTO P_RECHNUNG_ID FROM RECHNUNG;
    INSERT INTO RECHNUNG (RECHNUNG_ID, AUFTRAG_ID, KUNDE_ID, BETRAG) VALUES (P_RECHNUNG_ID, P_AUFTRAG_ID, V_KUNDE_ID, 0);
    P_ZAEHLER := P_ZAEHLER + 1;
  END;

  PROCEDURE OFFENE(P_KUNDE IN KUNDEN%ROWTYPE, P_CURSOR OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT * FROM RECHNUNG WHERE KUNDE_ID = P_KUNDE.KUNDE_ID AND GEDRUCKT_AM IS NULL;
  END;

  PROCEDURE AUFRAEUMEN IS
  BEGIN
    DELETE FROM RECHNUNG WHERE BETRAG = 0 AND GEDRUCKT_AM IS NULL;
  END;
END PKG_RECHNUNG;
/

CREATE OR REPLACE FUNCTION KUNDE_UMSATZ(P_KUNDE_ID NUMBER) RETURN NUMBER IS
  V_SUMME NUMBER;
BEGIN
  SELECT NVL(SUM(BETRAG), 0) INTO V_SUMME FROM RECHNUNG WHERE KUNDE_ID = P_KUNDE_ID;
  RETURN V_SUMME;
END;
/

CREATE OR REPLACE PROCEDURE NACHT_LAUF IS
BEGIN
  PKG_RECHNUNG.AUFRAEUMEN;
END;
/

-- Does not compile: the body refers to a column that does not exist (red in the explorer, errors in the tab).
CREATE OR REPLACE PACKAGE PKG_ALT AS
  PROCEDURE UEBERNEHME(P_KUNDE_ID NUMBER);
END PKG_ALT;
/

WHENEVER SQLERROR CONTINUE
CREATE OR REPLACE PACKAGE BODY PKG_ALT AS
  PROCEDURE UEBERNEHME(P_KUNDE_ID NUMBER) IS
  BEGIN
    UPDATE KUNDEN SET LETZTER_IMPORT = SYSDATE WHERE KUNDE_ID = P_KUNDE_ID;
  END;
END PKG_ALT;
/
WHENEVER SQLERROR EXIT FAILURE

-- Wrapped: the source is unreadable on purpose.
BEGIN
  DBMS_DDL.CREATE_WRAPPED('CREATE OR REPLACE PROCEDURE GEHEIM_BERECHNUNG(P_WERT NUMBER) IS BEGIN NULL; END;');
END;
/

-- A large package: 6,000 lines of constants and comments.
DECLARE
  V_TEXT CLOB;
  V_LINE VARCHAR2(200);
BEGIN
  DBMS_LOB.CREATETEMPORARY(V_TEXT, TRUE);
  V_LINE := 'CREATE OR REPLACE PACKAGE PKG_KONSTANTEN AS' || CHR(10);
  DBMS_LOB.WRITEAPPEND(V_TEXT, LENGTH(V_LINE), V_LINE);
  FOR I IN 1 .. 6000 LOOP
    -- Every fourth line a constant: 6,000 of them would be too large for one package (PLS-00123).
    V_LINE := CASE WHEN MOD(I, 4) = 0 THEN '  C_WERT_' || I || ' CONSTANT NUMBER := ' || I || ';' ELSE '  -- Zeile ' || I || ': Beschreibung des Werts' END || CHR(10);
    DBMS_LOB.WRITEAPPEND(V_TEXT, LENGTH(V_LINE), V_LINE);
  END LOOP;
  V_LINE := 'END PKG_KONSTANTEN;';
  DBMS_LOB.WRITEAPPEND(V_TEXT, LENGTH(V_LINE), V_LINE);
  EXECUTE IMMEDIATE V_TEXT;
END;
/

CREATE OR REPLACE TRIGGER RECHNUNG_BIU
BEFORE INSERT OR UPDATE ON RECHNUNG
FOR EACH ROW
WHEN (NEW.FAELLIG_AM IS NULL)
BEGIN
  -- Zahlungsziel: 14 Tage
  :NEW.FAELLIG_AM := TRUNC(SYSDATE) + 14;
END;
/

CREATE OR REPLACE TRIGGER AUFTRAG_AD
AFTER DELETE ON AUFTRAG
BEGIN
  NULL; -- früher: Protokoll
END;
/
ALTER TRIGGER AUFTRAG_AD DISABLE;
