using FerretSharp.Core.Compare;
using FerretSharp.Core.Schema;
using static FerretSharp.Core.Tests.Compare.TestComparison;

namespace FerretSharp.Core.Tests.Compare;

public class SchemaDdlTests
{
    private const string Ref = "DEV";
    private const string Tgt = "TEST";

    private static readonly ColumnInfo Id = Column("ID", "NUMBER", precision: 10, scale: 0, nullable: false);

    private static ObjectSnapshot Kunde(params ColumnInfo[] extra) =>
        Table("KUNDE", [Id, .. extra], [PrimaryKey("PK_KUNDE", "ID")], [UniqueIndex(Ref, "PK_KUNDE", On("ID"))]);

    private static DdlProposal Align(ObjectSnapshot? reference, ObjectSnapshot? target, CompareOptions? options = null) =>
        Align([.. reference is null ? Array.Empty<ObjectSnapshot>() : [reference]], [.. target is null ? Array.Empty<ObjectSnapshot>() : [target]], options);

    private static DdlProposal Align(ObjectSnapshot[] reference, ObjectSnapshot[] target, CompareOptions? options = null) =>
        SchemaDdl.Align(Of(options ?? new CompareOptions(Reference: 0), Snapshot(Ref, reference), Snapshot(Tgt, target)), 0, 1);

    private static string[] Sql(DdlProposal proposal) => proposal.Steps.Select(s => s.Sql).ToArray();

    private static DdlStep Single(DdlProposal proposal) => Assert.Single(proposal.Steps);

    // ---- objects ----

    [Fact]
    public void New_table_gets_create_table_with_exact_types_defaults_and_not_null()
    {
        var table = Table("AUFTRAG",
        [
            Column("ID", "NUMBER", identity: true),
            Column("NAME", "VARCHAR2", length: 50, charSemantics: true, nullable: false),
            Column("CODE", "VARCHAR2", length: 10, @default: "'X'"),
            Column("LAND", "CHAR", length: 2, defaultOnNull: true, @default: "'DE'"),
            Column("TEXT", "NVARCHAR2", length: 100),
            Column("BETRAG", "NUMBER", precision: 12, scale: 2),
            Column("MENGE", "NUMBER", scale: 0),
            Column("FAKTOR", "NUMBER", scale: 3),
            Column("WERT", "NUMBER"),
            Column("ZEIT", "TIMESTAMP(3)"),
            Column("DATUM", "DATE", nullable: false, @default: "SYSDATE"),
            Column("HASH", "RAW", length: 16),
            Column("NOTIZ", "CLOB"),
            Column("BRUTTO", "NUMBER", isVirtual: true, @default: "\"BETRAG\"*1.19"),
        ]);

        var step = Single(Align(table, null));

        Assert.Equal("AUFTRAG", step.Object);
        Assert.Equal(
            """
            CREATE TABLE "TEST"."AUFTRAG" (
                "ID" NUMBER GENERATED BY DEFAULT AS IDENTITY,
                "NAME" VARCHAR2(50 CHAR) NOT NULL,
                "CODE" VARCHAR2(10 BYTE) DEFAULT 'X',
                "LAND" CHAR(2 BYTE) DEFAULT ON NULL 'DE',
                "TEXT" NVARCHAR2(100),
                "BETRAG" NUMBER(12,2),
                "MENGE" INTEGER,
                "FAKTOR" NUMBER(*,3),
                "WERT" NUMBER,
                "ZEIT" TIMESTAMP(3),
                "DATUM" DATE DEFAULT SYSDATE NOT NULL,
                "HASH" RAW(16),
                "NOTIZ" CLOB,
                "BRUTTO" NUMBER GENERATED ALWAYS AS ("BETRAG"*1.19) VIRTUAL)
            """.ReplaceLineEndings("\n"),
            step.Sql);
        Assert.Contains("Identity ID", step.Warning);
        Assert.Contains("BY DEFAULT", step.Warning);
    }

    [Fact]
    public void New_table_adds_keys_checks_foreign_keys_and_indexes_after_all_tables()
    {
        var kunde = Kunde();
        var auftrag = Table("AUFTRAG",
            [Id, Column("KUNDE_ID", "NUMBER", precision: 10, scale: 0), Column("NR", "VARCHAR2", length: 20), Column("MENGE", "NUMBER")],
            [
                PrimaryKey("SYS_C001", "ID"),
                Unique("UQ_AUFTRAG_NR", "NR"),
                Check("SYS_C002", "MENGE > 0"),
                Check("CK_AUFTRAG_NR", "NR <> 'X'"),
                ForeignKey("FK_AUFTRAG_KUNDE", ["KUNDE_ID"], new TableRef(Ref, "KUNDE"), ["ID"], "CASCADE"),
            ],
            [
                UniqueIndex(Ref, "SYS_C001", On("ID")),
                UniqueIndex(Ref, "UQ_AUFTRAG_NR", On("NR")),
                Index(Ref, "IX_AUFTRAG_KUNDE", On("KUNDE_ID")),
            ]);

        var proposal = Align([auftrag, kunde], []);

        Assert.Equal(
            [
                "CREATE TABLE \"TEST\".\"AUFTRAG\" (\n    \"ID\" NUMBER(10) NOT NULL,\n    \"KUNDE_ID\" NUMBER(10),\n    \"NR\" VARCHAR2(20 BYTE),\n    \"MENGE\" NUMBER)",
                "CREATE TABLE \"TEST\".\"KUNDE\" (\n    \"ID\" NUMBER(10) NOT NULL)",
                "ALTER TABLE \"TEST\".\"AUFTRAG\" ADD PRIMARY KEY (\"ID\")",
                "ALTER TABLE \"TEST\".\"AUFTRAG\" ADD CONSTRAINT \"UQ_AUFTRAG_NR\" UNIQUE (\"NR\")",
                "ALTER TABLE \"TEST\".\"KUNDE\" ADD CONSTRAINT \"PK_KUNDE\" PRIMARY KEY (\"ID\")",
                "ALTER TABLE \"TEST\".\"AUFTRAG\" ADD CHECK (MENGE > 0)",
                "ALTER TABLE \"TEST\".\"AUFTRAG\" ADD CONSTRAINT \"CK_AUFTRAG_NR\" CHECK (NR <> 'X')",
                "ALTER TABLE \"TEST\".\"AUFTRAG\" ADD CONSTRAINT \"FK_AUFTRAG_KUNDE\" FOREIGN KEY (\"KUNDE_ID\") REFERENCES \"TEST\".\"KUNDE\" (\"ID\") ON DELETE CASCADE",
                "CREATE INDEX \"TEST\".\"IX_AUFTRAG_KUNDE\" ON \"TEST\".\"AUFTRAG\" (\"KUNDE_ID\")",
            ],
            Sql(proposal));
        Assert.All(proposal.Steps, s => Assert.Null(s.Warning)); // a new table has no rows to fail on
    }

    [Fact]
    public void Key_whose_index_has_its_own_name_creates_it_with_using_index()
    {
        var table = Table("KUNDE", [Id], [PrimaryKey("PK_KUNDE", "ID")], [UniqueIndex(Ref, "KUNDE_ID_UX", On("ID"))]);

        var proposal = Align(table, null);

        Assert.Equal(
            "ALTER TABLE \"TEST\".\"KUNDE\" ADD CONSTRAINT \"PK_KUNDE\" PRIMARY KEY (\"ID\") USING INDEX (CREATE UNIQUE INDEX \"TEST\".\"KUNDE_ID_UX\" ON \"TEST\".\"KUNDE\" (\"ID\"))",
            proposal.Steps[1].Sql);
        Assert.Equal(2, proposal.Steps.Count);
    }

    [Fact]
    public void Deferrable_key_brings_its_non_unique_index()
    {
        // A deferrable key cannot use a unique index (ORA-14196): its index in the reference is a normal one.
        var table = Table("KUNDE", [Id], [PrimaryKey("PK_KUNDE", "ID") with { Deferrable = true }], [Index(Ref, "KUNDE_ID_IX", On("ID"))]);

        var proposal = Align(table, null);

        Assert.Equal(
            "ALTER TABLE \"TEST\".\"KUNDE\" ADD CONSTRAINT \"PK_KUNDE\" PRIMARY KEY (\"ID\") DEFERRABLE USING INDEX (CREATE INDEX \"TEST\".\"KUNDE_ID_IX\" ON \"TEST\".\"KUNDE\" (\"ID\"))",
            proposal.Steps[1].Sql);
        Assert.Equal(2, proposal.Steps.Count);
    }

    [Fact]
    public void Foreign_key_to_another_schema_keeps_its_owner()
    {
        var table = Table("AUFTRAG", [Id], [ForeignKey("FK_LAND", ["ID"], new TableRef("STAMM", "LAND"), ["ID"], "SET NULL", deferred: true)]);

        var step = Align(table, null).Steps[1];

        Assert.Equal("ALTER TABLE \"TEST\".\"AUFTRAG\" ADD CONSTRAINT \"FK_LAND\" FOREIGN KEY (\"ID\") REFERENCES \"STAMM\".\"LAND\" (\"ID\") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED", step.Sql);
    }

    [Fact]
    public void Index_organized_table_has_its_primary_key_inline()
    {
        var table = Table("POS", [Id, Column("NR", "NUMBER", nullable: false)], [PrimaryKey("PK_POS", "ID", "NR")],
            [UniqueIndex(Ref, "PK_POS", On("ID"), On("NR")) with { IndexType = "IOT - TOP" }], iot: true);

        var step = Single(Align(table, null));

        Assert.Equal("CREATE TABLE \"TEST\".\"POS\" (\n    \"ID\" NUMBER(10) NOT NULL,\n    \"NR\" NUMBER NOT NULL,\n    CONSTRAINT \"PK_POS\" PRIMARY KEY (\"ID\", \"NR\")) ORGANIZATION INDEX", step.Sql);
    }

    [Fact]
    public void Temporary_and_partitioned_tables_warn_about_what_is_not_known()
    {
        var proposal = Align([Table("TMP", [Id], temporary: true), Table("PART", [Id], partitioned: true)], []);

        Assert.StartsWith("CREATE TABLE \"TEST\".\"PART\"", proposal.Steps[0].Sql);
        Assert.Contains("Partitionierung", proposal.Steps[0].Warning);
        Assert.StartsWith("CREATE GLOBAL TEMPORARY TABLE \"TEST\".\"TMP\"", proposal.Steps[1].Sql);
        Assert.Contains("ON COMMIT", proposal.Steps[1].Warning);
    }

    [Theory]
    [InlineData(TableKind.View, "-- CREATE VIEW \"TEST\".\"V_KUNDE\" AS …")]
    [InlineData(TableKind.MaterializedView, "-- CREATE MATERIALIZED VIEW \"TEST\".\"V_KUNDE\" AS …")]
    public void View_only_in_reference_is_a_hint_to_take_the_definition(TableKind kind, string sql)
    {
        var step = Single(Align(Table("V_KUNDE", [Id], kind: kind), null));

        Assert.Equal(sql, step.Sql);
        Assert.True(step.IsCommented);
        Assert.Contains("DDL-Ansicht der Referenz", step.Warning);
    }

    [Theory]
    [InlineData(TableKind.Table, "-- DROP TABLE \"TEST\".\"ALT\"", "mit allen Daten")]
    [InlineData(TableKind.View, "-- DROP VIEW \"TEST\".\"ALT\"", "ungültig")]
    [InlineData(TableKind.MaterializedView, "-- DROP MATERIALIZED VIEW \"TEST\".\"ALT\"", "mit allen Daten")]
    public void Object_only_in_target_is_a_commented_drop(TableKind kind, string sql, string warning)
    {
        var step = Single(Align(null, Table("ALT", [Id], kind: kind)));

        Assert.Equal(sql, step.Sql);
        Assert.Contains(warning, step.Warning);
    }

    [Fact]
    public void Object_in_other_case_is_a_rename_hint()
    {
        var step = Single(Align(Table("Kunde", [Id]), Table("KUNDE", [Id])));

        Assert.Equal("-- ALTER TABLE \"TEST\".\"KUNDE\" RENAME TO \"Kunde\"", step.Sql);
        Assert.Contains("EF Core", step.Warning);
    }

    [Fact]
    public void Table_against_view_is_only_a_hint()
    {
        var step = Single(Align(Table("KUNDE", [Id]), Table("KUNDE", [Id], kind: TableKind.View)));

        Assert.True(step.IsCommented);
        Assert.Contains("Referenz Tabelle, im Ziel View", step.Sql);
        Assert.NotNull(step.Warning);
    }

    [Fact]
    public void Different_organization_is_only_a_hint()
    {
        var step = Single(Align(Table("KUNDE", [Id], iot: true), Table("KUNDE", [Id])));

        Assert.True(step.IsCommented);
        Assert.Contains("index-organisiert", step.Sql);
    }

    [Fact]
    public void Differing_view_columns_point_to_the_definition()
    {
        var step = Single(Align(
            Table("V_KUNDE", [Id, Column("NAME", "VARCHAR2", length: 50)], kind: TableKind.View),
            Table("V_KUNDE", [Id], kind: TableKind.View)));

        Assert.Equal("-- CREATE OR REPLACE VIEW \"TEST\".\"V_KUNDE\" AS …  (abweichend: NAME)", step.Sql);
    }

    // ---- columns ----

    [Fact]
    public void Missing_column_is_added_and_not_null_without_default_warns()
    {
        var proposal = Align(
            Kunde(Column("NAME", "VARCHAR2", length: 50, charSemantics: true, nullable: false),
                Column("STATUS", "CHAR", length: 1, nullable: false, @default: "'A'"),
                Column("EMAIL", "VARCHAR2", length: 200, charSemantics: true, comment: "Adresse")),
            Kunde());

        Assert.Equal(
            [
                "ALTER TABLE \"TEST\".\"KUNDE\" ADD (\"NAME\" VARCHAR2(50 CHAR) NOT NULL)",
                "ALTER TABLE \"TEST\".\"KUNDE\" ADD (\"STATUS\" CHAR(1 BYTE) DEFAULT 'A' NOT NULL)",
                "ALTER TABLE \"TEST\".\"KUNDE\" ADD (\"EMAIL\" VARCHAR2(200 CHAR))",
                "COMMENT ON COLUMN \"TEST\".\"KUNDE\".\"EMAIL\" IS 'Adresse'",
            ],
            Sql(proposal));
        Assert.Equal("Schlägt fehl, wenn die Tabelle Zeilen hat (NOT NULL ohne Default).", proposal.Steps[0].Warning);
        Assert.Null(proposal.Steps[1].Warning);
    }

    [Fact]
    public void Column_only_in_target_is_a_commented_drop()
    {
        var step = Single(Align(Kunde(), Kunde(Column("ALT", "NUMBER"))));

        Assert.Equal("-- ALTER TABLE \"TEST\".\"KUNDE\" DROP COLUMN \"ALT\"", step.Sql);
        Assert.Equal("Löscht die Spalte mit ihren Daten.", step.Warning);
    }

    [Theory]
    [InlineData("VARCHAR2", 100, true, null, null, "VARCHAR2", 50, true, null, null, "VARCHAR2(100 CHAR)", false)]
    [InlineData("VARCHAR2", 30, true, null, null, "VARCHAR2", 50, true, null, null, "VARCHAR2(30 CHAR)", true)]
    [InlineData("VARCHAR2", 50, true, null, null, "VARCHAR2", 50, false, null, null, "VARCHAR2(50 CHAR)", true)]
    [InlineData("NUMBER", null, false, 12, 2, "NUMBER", null, false, 10, 2, "NUMBER(12,2)", false)]
    [InlineData("NUMBER", null, false, 8, 2, "NUMBER", null, false, 10, 2, "NUMBER(8,2)", true)]
    [InlineData("NUMBER", null, false, 10, 3, "NUMBER", null, false, 10, 2, "NUMBER(10,3)", true)]
    [InlineData("TIMESTAMP(6)", null, false, null, 6, "DATE", null, false, null, null, "TIMESTAMP(6)", true)]
    [InlineData("RAW", 32, false, null, null, "RAW", 16, false, null, null, "RAW(32)", false)]
    public void Type_change_within_a_family_is_a_modify(
        string type, int? length, bool chars, int? precision, int? scale,
        string targetType, int? targetLength, bool targetChars, int? targetPrecision, int? targetScale,
        string expected, bool warns)
    {
        var step = Single(Align(
            Kunde(Column("X", type, length, chars, precision, scale)),
            Kunde(Column("X", targetType, targetLength, targetChars, targetPrecision, targetScale))));

        Assert.Equal($"ALTER TABLE \"TEST\".\"KUNDE\" MODIFY (\"X\" {expected})", step.Sql);
        Assert.Equal(warns ? "Kann an vorhandenen Daten scheitern (Länge, Genauigkeit oder BYTE/CHAR)." : null, step.Warning);
    }

    [Theory]
    [InlineData("NUMBER", "VARCHAR2")]
    [InlineData("CLOB", "VARCHAR2")]
    [InlineData("VARCHAR2", "CLOB")]
    [InlineData("DATE", "NUMBER")]
    public void Type_change_across_families_or_lobs_is_only_a_hint(string type, string targetType)
    {
        var step = Single(Align(
            Kunde(Column("X", type, length: type == "VARCHAR2" ? 10 : null)),
            Kunde(Column("X", targetType, length: targetType == "VARCHAR2" ? 10 : null))));

        Assert.True(step.IsCommented);
        Assert.Contains("neue Spalte", step.Warning);
    }

    [Fact]
    public void Nullability_changes_in_both_directions()
    {
        var proposal = Align(
            Kunde(Column("A", "NUMBER", nullable: false), Column("B", "NUMBER")),
            Kunde(Column("A", "NUMBER"), Column("B", "NUMBER", nullable: false)));

        Assert.Equal(["ALTER TABLE \"TEST\".\"KUNDE\" MODIFY (\"A\" NOT NULL)", "ALTER TABLE \"TEST\".\"KUNDE\" MODIFY (\"B\" NULL)"], Sql(proposal));
        Assert.Equal("Schlägt fehl, wenn die Tabelle Zeilen mit NULL in dieser Spalte hat.", proposal.Steps[0].Warning);
        Assert.Null(proposal.Steps[1].Warning);
    }

    [Fact]
    public void Default_changes_set_replace_or_remove_it()
    {
        var proposal = Align(
            Kunde(Column("A", "CHAR", 1, @default: "'J'"), Column("B", "CHAR", 1), Column("C", "CHAR", 1, @default: "'N'", defaultOnNull: true)),
            Kunde(Column("A", "CHAR", 1, @default: "'N'"), Column("B", "CHAR", 1, @default: "'N'"), Column("C", "CHAR", 1, @default: "'N'")));

        Assert.Equal(
            [
                "ALTER TABLE \"TEST\".\"KUNDE\" MODIFY (\"A\" DEFAULT 'J')",
                "ALTER TABLE \"TEST\".\"KUNDE\" MODIFY (\"B\" DEFAULT NULL)",
                "ALTER TABLE \"TEST\".\"KUNDE\" MODIFY (\"C\" DEFAULT ON NULL 'N')",
            ],
            Sql(proposal));
        Assert.Contains("NOT NULL", proposal.Steps[2].Warning);
    }

    [Fact]
    public void Dropping_default_on_null_leaves_null_to_a_hint()
    {
        // Oracle 23 takes NOT NULL away with ON NULL; MODIFY NULL would then fail with ORA-01451.
        var proposal = Align(
            Kunde(Column("C", "CHAR", 1, @default: "'N'")),
            Kunde(Column("C", "CHAR", 1, @default: "'N'", defaultOnNull: true)));

        Assert.Equal(["ALTER TABLE \"TEST\".\"KUNDE\" MODIFY (\"C\" DEFAULT 'N')", "-- ALTER TABLE \"TEST\".\"KUNDE\" MODIFY (\"C\" NULL)"], Sql(proposal));
        Assert.Contains("Oracle 23", proposal.Steps[1].Warning);
    }

    [Fact]
    public void Dropping_default_on_null_of_a_not_null_column_sets_not_null_again()
    {
        var proposal = Align(
            Kunde(Column("C", "CHAR", 1, @default: "'N'", nullable: false)),
            Kunde(Column("C", "CHAR", 1, @default: "'N'", defaultOnNull: true)));

        Assert.Equal(["ALTER TABLE \"TEST\".\"KUNDE\" MODIFY (\"C\" DEFAULT 'N')", "ALTER TABLE \"TEST\".\"KUNDE\" MODIFY (\"C\" NOT NULL)"], Sql(proposal));
        Assert.Contains("ORA-01442", proposal.Steps[1].Warning);
    }

    [Fact]
    public void Identity_or_virtual_change_is_only_a_hint()
    {
        var proposal = Align(
            Kunde(Column("A", "NUMBER", identity: true), Column("B", "NUMBER", isVirtual: true, @default: "ID*2")),
            Kunde(Column("A", "NUMBER"), Column("B", "NUMBER", isVirtual: true, @default: "ID*3")));

        Assert.Equal(2, proposal.Steps.Count);
        Assert.All(proposal.Steps, s => Assert.True(s.IsCommented));
        Assert.All(proposal.Steps, s => Assert.Contains("nicht per MODIFY", s.Warning));
    }

    [Fact]
    public void Column_comment_is_set_or_cleared()
    {
        var proposal = Align(Kunde(Column("A", "NUMBER", comment: "Menge in 'Stück'"), Column("B", "NUMBER")),
            Kunde(Column("A", "NUMBER"), Column("B", "NUMBER", comment: "alt")));

        Assert.Equal(
            ["COMMENT ON COLUMN \"TEST\".\"KUNDE\".\"A\" IS 'Menge in ''Stück'''", "COMMENT ON COLUMN \"TEST\".\"KUNDE\".\"B\" IS ''"],
            Sql(proposal));
    }

    [Fact]
    public void Column_in_other_case_is_a_rename_hint()
    {
        var step = Single(Align(Kunde(Column("eMail", "NUMBER")), Kunde(Column("EMAIL", "NUMBER"))));

        Assert.Equal("-- ALTER TABLE \"TEST\".\"KUNDE\" RENAME COLUMN \"EMAIL\" TO \"eMail\"", step.Sql);
    }

    [Fact]
    public void Column_order_is_a_hint_only_when_it_counts()
    {
        ObjectSnapshot reference = Kunde(Column("A", "NUMBER"), Column("B", "NUMBER"));
        ObjectSnapshot target = Kunde(Column("B", "NUMBER"), Column("A", "NUMBER"));

        Assert.Empty(Align(reference, target).Steps);

        var step = Single(Align(reference, target, new CompareOptions(Reference: 0, ColumnOrder: true)));
        Assert.Equal("-- \"TEST\".\"KUNDE\": Spaltenreihenfolge weicht ab (ID, A, B)", step.Sql);
        Assert.Contains("nicht umsortieren", step.Warning);
    }

    [Fact]
    public void Expression_naming_the_reference_schema_warns()
    {
        var step = Single(Align(Kunde(Column("NR", "NUMBER", @default: "\"DEV\".\"SEQ_NR\".nextval")), Kunde()));

        Assert.Equal("Der Ausdruck nennt das Schema der Referenz (DEV) – im Ziel anpassen.", step.Warning);
    }

    // ---- constraints ----

    [Fact]
    public void Missing_constraints_are_added_with_their_state()
    {
        var reference = Table("KUNDE", [Id, Column("NR", "NUMBER")],
        [
            Check("CK_NR", "NR > 0", enabled: false),
            Check("CK_NR2", "NR < 10") with { Validated = false },
            Unique("UQ_NR", "NR") with { Deferrable = true },
        ]);

        var proposal = Align(reference, Table("KUNDE", [Id, Column("NR", "NUMBER")]));

        Assert.Equal(
            [
                "ALTER TABLE \"TEST\".\"KUNDE\" ADD CONSTRAINT \"UQ_NR\" UNIQUE (\"NR\") DEFERRABLE",
                "ALTER TABLE \"TEST\".\"KUNDE\" ADD CONSTRAINT \"CK_NR\" CHECK (NR > 0) DISABLE",
                "ALTER TABLE \"TEST\".\"KUNDE\" ADD CONSTRAINT \"CK_NR2\" CHECK (NR < 10) ENABLE NOVALIDATE",
            ],
            Sql(proposal));
        Assert.Equal("Prüft die vorhandenen Zeilen und scheitert bei Verstößen.", proposal.Steps[0].Warning);
        Assert.Null(proposal.Steps[1].Warning);
    }

    [Fact]
    public void Extra_constraint_is_a_commented_drop_with_its_own_name()
    {
        var proposal = Align(Kunde(), Table("KUNDE", [Id], [PrimaryKey("PK_KUNDE", "ID"), Check("SYS_C0042", "ID > 0")], [UniqueIndex(Tgt, "PK_KUNDE", On("ID"))]));

        var step = Single(proposal);
        Assert.Equal("-- ALTER TABLE \"TEST\".\"KUNDE\" DROP CONSTRAINT \"SYS_C0042\"", step.Sql);
        Assert.Equal("Löscht die Prüfung.", step.Warning);
    }

    [Fact]
    public void Different_constraint_is_dropped_and_added()
    {
        var proposal = Align(
            Table("KUNDE", [Id], [PrimaryKey("PK_KUNDE", "ID"), Check("CK_ID", "ID > 0")]),
            Table("KUNDE", [Id], [PrimaryKey("PK_KUNDE", "ID"), Check("CK_ID", "ID >= 0")]));

        Assert.Equal(["ALTER TABLE \"TEST\".\"KUNDE\" DROP CONSTRAINT \"CK_ID\"", "ALTER TABLE \"TEST\".\"KUNDE\" ADD CONSTRAINT \"CK_ID\" CHECK (ID > 0)"], Sql(proposal));
        Assert.Contains("gelöscht und neu angelegt", proposal.Steps[0].Warning);
    }

    [Fact]
    public void Different_primary_key_warns_about_foreign_keys()
    {
        var proposal = Align(
            Table("KUNDE", [Id, Column("NR", "NUMBER", nullable: false)], [PrimaryKey("PK_KUNDE", "ID", "NR")]),
            Table("KUNDE", [Id, Column("NR", "NUMBER", nullable: false)], [PrimaryKey("PK_KUNDE", "ID")]));

        Assert.Equal("ALTER TABLE \"TEST\".\"KUNDE\" DROP CONSTRAINT \"PK_KUNDE\"", proposal.Steps[0].Sql);
        Assert.Contains("ORA-02273", proposal.Steps[0].Warning);
        Assert.Equal("ALTER TABLE \"TEST\".\"KUNDE\" ADD CONSTRAINT \"PK_KUNDE\" PRIMARY KEY (\"ID\", \"NR\")", proposal.Steps[1].Sql);
    }

    [Fact]
    public void Generated_names_on_both_sides_are_not_a_difference()
    {
        var proposal = Align(
            Table("KUNDE", [Id], [Check("SYS_C001", "ID > 0")]),
            Table("KUNDE", [Id], [Check("SYS_C987", "ID > 0")]));

        Assert.Empty(proposal.Steps);
    }

    // ---- indexes ----

    [Fact]
    public void Missing_indexes_are_created_with_their_kind_and_columns()
    {
        var columns = new[] { Id, Column("NAME", "VARCHAR2", length: 50), Column("LAND", "CHAR", length: 2) };
        var reference = Table("KUNDE", columns, [], [
            Index(Ref, "IX_NAME", Expression("UPPER(\"NAME\")"), On("LAND", descending: true)),
            Index(Ref, "IX_LAND", On("LAND")) with { IndexType = "BITMAP" },
            UniqueIndex(Ref, "UX_NAME", On("NAME"), On("ID")) with { Visible = false },
            Index(Ref, "IX_REV", On("ID")) with { IndexType = "NORMAL/REV" },
        ]);

        var proposal = Align(reference, Table("KUNDE", columns));

        Assert.Equal(
            [
                "CREATE BITMAP INDEX \"TEST\".\"IX_LAND\" ON \"TEST\".\"KUNDE\" (\"LAND\")",
                "CREATE INDEX \"TEST\".\"IX_NAME\" ON \"TEST\".\"KUNDE\" (UPPER(\"NAME\"), \"LAND\" DESC)",
                "CREATE INDEX \"TEST\".\"IX_REV\" ON \"TEST\".\"KUNDE\" (\"ID\") REVERSE",
                "CREATE UNIQUE INDEX \"TEST\".\"UX_NAME\" ON \"TEST\".\"KUNDE\" (\"NAME\", \"ID\") INVISIBLE",
            ],
            Sql(proposal).Order(StringComparer.Ordinal));
    }

    [Fact]
    public void Index_with_a_generated_name_gets_a_readable_one()
    {
        var reference = Table("KUNDE", [Id, Column("NR", "NUMBER")], [], [Index(Ref, "SYS_C0099", On("NR"), On("ID"))]);

        var step = Single(Align(reference, Table("KUNDE", [Id, Column("NR", "NUMBER")])));

        Assert.Equal("CREATE INDEX \"TEST\".\"IX_KUNDE_NR_ID\" ON \"TEST\".\"KUNDE\" (\"NR\", \"ID\")", step.Sql);
        Assert.Contains("SYS_C0099", step.Warning);
    }

    [Fact]
    public void Index_on_columns_the_target_indexes_under_another_name_is_a_rename_hint()
    {
        var step = Align(
            Table("KUNDE", [Id, Column("NR", "NUMBER")], [], [Index(Ref, "IX_NR", On("NR"))]),
            Table("KUNDE", [Id, Column("NR", "NUMBER")], [], [Index(Tgt, "KUNDE_NR_IDX", On("NR"))])).Steps;

        Assert.Equal(
            ["-- ALTER INDEX \"TEST\".\"KUNDE_NR_IDX\" RENAME TO \"IX_NR\"", "-- DROP INDEX \"TEST\".\"KUNDE_NR_IDX\""],
            step.Select(s => s.Sql).Order(StringComparer.Ordinal));
        Assert.All(step, s => Assert.True(s.IsCommented));
    }

    [Fact]
    public void Extra_and_different_indexes()
    {
        var proposal = Align(
            Table("KUNDE", [Id, Column("NR", "NUMBER")], [], [Index(Ref, "IX_NR", On("NR"), On("ID"))]),
            Table("KUNDE", [Id, Column("NR", "NUMBER")], [], [Index(Tgt, "IX_NR", On("NR")), Index(Tgt, "IX_ALT", On("ID"))]));

        Assert.Equal(
            [
                "DROP INDEX \"TEST\".\"IX_NR\"",
                "CREATE INDEX \"TEST\".\"IX_NR\" ON \"TEST\".\"KUNDE\" (\"NR\", \"ID\")",
                "-- DROP INDEX \"TEST\".\"IX_ALT\"",
            ],
            Sql(proposal));
        Assert.Contains("ORA-02429", proposal.Steps[0].Warning);
        Assert.Equal("Löscht den Index. Stützt er einen Schlüssel, lehnt Oracle das ab (ORA-02429).", proposal.Steps[2].Warning);
    }

    [Fact]
    public void Index_backing_a_key_added_in_the_proposal_is_left_to_oracle()
    {
        var proposal = Align(
            Table("KUNDE", [Id, Column("NR", "NUMBER")], [Unique("UQ_NR", "NR")], [UniqueIndex(Ref, "UQ_NR", On("NR"))]),
            Table("KUNDE", [Id, Column("NR", "NUMBER")]));

        Assert.Equal(["ALTER TABLE \"TEST\".\"KUNDE\" ADD CONSTRAINT \"UQ_NR\" UNIQUE (\"NR\")"], Sql(proposal));
    }

    [Fact]
    public void Backing_index_is_recognized_when_the_cells_carry_copies()
    {
        var comparison = Of(
            Snapshot(Ref, Table("KUNDE", [Id, Column("NR", "NUMBER")], [Unique("UQ_NR", "NR")], [UniqueIndex(Ref, "UQ_NR", On("NR"))])),
            Snapshot(Tgt, Table("KUNDE", [Id, Column("NR", "NUMBER")])));
        var row = comparison.Objects[0];
        var children = row.Children.Select(c => c with
        {
            Cells = c.Cells.Select(cell => cell.Index is { } index ? cell with { Index = index with { Columns = index.Columns.ToList() } } : cell).ToList(),
        }).ToList();

        var proposal = SchemaDdl.Align(comparison with { Objects = [row with { Children = children }] }, 0, 1);

        Assert.Equal(["ALTER TABLE \"TEST\".\"KUNDE\" ADD CONSTRAINT \"UQ_NR\" UNIQUE (\"NR\")"], Sql(proposal));
    }

    [Fact]
    public void Domain_index_is_only_a_hint()
    {
        var step = Single(Align(
            Table("KUNDE", [Id], [], [Index(Ref, "IX_TEXT", On("ID")) with { IndexType = "DOMAIN" }]),
            Table("KUNDE", [Id])));

        Assert.True(step.IsCommented);
        Assert.Contains("DOMAIN", step.Sql);
    }

    // ---- order, filter, quoting ----

    [Fact]
    public void Steps_follow_the_phases_then_object_names()
    {
        var reference = new[]
        {
            Table("B", [Id, Column("X", "NUMBER")], [Check("CK_B", "X > 0"), ForeignKey("FK_B_A", ["ID"], new TableRef(Ref, "A"), ["ID"])], [Index(Ref, "IX_B", On("X"))]),
            Table("A", [Id], [PrimaryKey("PK_A", "ID")]),
        };
        var target = new[] { Table("B", [Id]), Table("Z", [Id]) };

        var proposal = Align(reference, target);

        Assert.Equal(
            [
                "CREATE TABLE \"TEST\".\"A\" (\n    \"ID\" NUMBER(10) NOT NULL)",
                "ALTER TABLE \"TEST\".\"B\" ADD (\"X\" NUMBER)",
                "ALTER TABLE \"TEST\".\"A\" ADD CONSTRAINT \"PK_A\" PRIMARY KEY (\"ID\")",
                "ALTER TABLE \"TEST\".\"B\" ADD CONSTRAINT \"CK_B\" CHECK (X > 0)",
                "ALTER TABLE \"TEST\".\"B\" ADD CONSTRAINT \"FK_B_A\" FOREIGN KEY (\"ID\") REFERENCES \"TEST\".\"A\" (\"ID\")",
                "CREATE INDEX \"TEST\".\"IX_B\" ON \"TEST\".\"B\" (\"X\")",
                "-- DROP TABLE \"TEST\".\"Z\"",
            ],
            Sql(proposal));
    }

    [Fact]
    public void Rows_limit_the_proposal_and_null_takes_all_differing_objects()
    {
        var comparison = Of(Snapshot(Ref, Table("A", [Id]), Table("B", [Id]), Table("C", [Id])), Snapshot(Tgt, Table("C", [Id])));

        Assert.Equal(["A", "B"], SchemaDdl.Align(comparison, 0, 1).Steps.Select(s => s.Object));
        Assert.Equal(["B"], SchemaDdl.Align(comparison, 0, 1, [comparison.Objects[1]]).Steps.Select(s => s.Object));
        Assert.Empty(SchemaDdl.Align(comparison, 0, 1, [comparison.Objects[2]]).Steps);
    }

    [Fact]
    public void Only_reference_and_target_count()
    {
        // Side 0 differs from both others; side 1 and 2 agree, and the comparison's own reference is side 0.
        var comparison = Of(
            Snapshot("DEV", Table("A", [Id, Column("X", "NUMBER")])),
            Snapshot("TEST", Table("A", [Id])),
            Snapshot("PROD", Table("A", [Id])));

        Assert.Empty(SchemaDdl.Align(comparison, 1, 2).Steps);
        Assert.Equal(["-- ALTER TABLE \"DEV\".\"A\" DROP COLUMN \"X\""], SchemaDdl.Align(comparison, 2, 0).Steps.Select(s => s.Sql));
        Assert.Equal(["ALTER TABLE \"PROD\".\"A\" ADD (\"X\" NUMBER)"], SchemaDdl.Align(comparison, 0, 2).Steps.Select(s => s.Sql));
    }

    [Fact]
    public void Mixed_case_names_are_quoted_exactly()
    {
        var reference = Table("Kunden", [Column("Id", "NUMBER", nullable: false), Column("eMail", "VARCHAR2", length: 100)],
            [PrimaryKey("Pk_Kunden", "Id")], [Index("Dev", "Ix_Mail", On("eMail"))]);

        var proposal = SchemaDdl.Align(Of(Snapshot("Dev", reference), Snapshot("Test")), 0, 1);

        Assert.Equal(
            [
                "CREATE TABLE \"Test\".\"Kunden\" (\n    \"Id\" NUMBER NOT NULL,\n    \"eMail\" VARCHAR2(100 BYTE))",
                "ALTER TABLE \"Test\".\"Kunden\" ADD CONSTRAINT \"Pk_Kunden\" PRIMARY KEY (\"Id\")",
                "CREATE INDEX \"Test\".\"Ix_Mail\" ON \"Test\".\"Kunden\" (\"eMail\")",
            ],
            Sql(proposal));
    }

    [Fact]
    public void Same_side_twice_is_refused()
    {
        var comparison = Of(Snapshot(Ref), Snapshot(Tgt));

        Assert.Throws<ArgumentException>(() => SchemaDdl.Align(comparison, 1, 1));
        Assert.Throws<ArgumentOutOfRangeException>(() => SchemaDdl.Align(comparison, 0, 2));
    }

    // ---- script ----

    [Fact]
    public void Script_has_header_warnings_statements_and_commented_hints()
    {
        var proposal = Align(
            [Table("NEU", [Id, Column("N", "NUMBER")]), Kunde(Column("A", "NUMBER", nullable: false))],
            [Kunde(), Table("ALT", [Id])]);

        var lines = proposal.Script.ReplaceLineEndings("\n").Split('\n');

        Assert.Equal(
            [
                "-- DDL-Vorschlag: TEST (Seite 2) an die Referenz DEV (Seite 1) angleichen.",
                "-- Von FerretSharp erzeugt, nicht ausgeführt: vor dem Ausführen prüfen. Auskommentiertes bewusst entscheiden.",
                "",
                "CREATE TABLE \"TEST\".\"NEU\" (",
                "    \"ID\" NUMBER(10) NOT NULL,",
                "    \"N\" NUMBER);",
                "",
                "-- ⚠ Schlägt fehl, wenn die Tabelle Zeilen hat (NOT NULL ohne Default).",
                "ALTER TABLE \"TEST\".\"KUNDE\" ADD (\"A\" NUMBER NOT NULL);",
                "",
                "-- ⚠ Löscht die Tabelle mit allen Daten.",
                "-- DROP TABLE \"TEST\".\"ALT\"",
                "",
            ],
            lines);
    }

    [Fact]
    public void Script_comments_every_line_of_a_multi_line_hint_and_every_warning_line()
    {
        var proposal = new DdlProposal(0, 1, [new DdlStep("X", "-- CREATE VIEW X AS\nSELECT 1 FROM DUAL", "Erste Zeile\nZweite Zeile")]);

        var lines = proposal.Script.ReplaceLineEndings("\n").Split('\n');

        Assert.Equal("-- DDL-Vorschlag: Seite 2 an die Referenz Seite 1 angleichen.", lines[0]);
        Assert.Equal(["-- ⚠ Erste Zeile", "-- ⚠ Zweite Zeile", "-- CREATE VIEW X AS", "-- SELECT 1 FROM DUAL", ""], lines[3..]);
        Assert.DoesNotContain(lines, l => l.Length > 0 && !l.StartsWith("--", StringComparison.Ordinal));
    }

    [Fact]
    public void Script_without_steps_says_so()
    {
        var proposal = Align(Kunde(), Kunde());

        Assert.Empty(proposal.Steps);
        Assert.Contains("-- Keine Unterschiede.", proposal.Script, StringComparison.Ordinal);
    }
}
