using System.Text;
using FerretSharp.Core.Oracle;
using FerretSharp.Core.Resources;
using FerretSharp.Core.Schema;

namespace FerretSharp.Core.Compare;

/// <summary>
/// SQL fragments of the DDL proposal (<see cref="SchemaDdl"/>). Text for the user to copy: FerretSharp does not run it
/// (WP-20); names are always quoted exactly as in the dictionary.
/// </summary>
internal static class DdlText
{
    public static string Q(string name) => OracleIdentifier.Quote(name);

    /// <summary><c>"NAME" type [AS (…) | identity | DEFAULT …] [NOT NULL]</c> for CREATE TABLE and ADD.</summary>
    public static string ColumnDefinition(ColumnInfo column)
    {
        var sql = new StringBuilder($"{Q(column.Name)} {OracleTypes.DdlType(column)}");
        if (column.IsVirtual)
        {
            sql.Append($" GENERATED ALWAYS AS ({column.Default}) VIRTUAL");
        }
        else if (column.IsIdentity)
        {
            sql.Append(column.DefaultOnNull ? " GENERATED BY DEFAULT ON NULL AS IDENTITY" : " GENERATED BY DEFAULT AS IDENTITY");
        }
        else if (column.Default is { } value)
        {
            sql.Append(column.DefaultOnNull ? $" DEFAULT ON NULL {value}" : $" DEFAULT {value}");
        }

        // Identity and DEFAULT ON NULL columns are NOT NULL by themselves.
        if (!column.Nullable && !column.IsIdentity && !column.DefaultOnNull)
        {
            sql.Append(" NOT NULL");
        }

        return sql.ToString();
    }

    /// <summary>
    /// The constraint as it follows <c>ADD</c> (or stands in a CREATE TABLE): named unless Oracle generated the name in
    /// the reference, then Oracle names it again. <paramref name="usingIndex"/>: an index of another name backing the key.
    /// </summary>
    public static string ConstraintClause(ConstraintInfo constraint, Func<TableRef, TableRef> mapTable, string? usingIndex = null)
    {
        var sql = new StringBuilder();
        if (!constraint.GeneratedName)
        {
            sql.Append($"CONSTRAINT {Q(constraint.Name)} ");
        }

        switch (constraint.Type)
        {
            case ConstraintType.PrimaryKey:
                sql.Append($"PRIMARY KEY ({Columns(constraint.Columns)})");
                break;
            case ConstraintType.Unique:
                sql.Append($"UNIQUE ({Columns(constraint.Columns)})");
                break;
            case ConstraintType.Check:
                sql.Append($"CHECK ({constraint.Condition})");
                break;
            case ConstraintType.ForeignKey:
                var to = mapTable(constraint.References ?? throw new ArgumentException($"Foreign key {constraint.Name} without referenced table.", nameof(constraint)));
                sql.Append($"FOREIGN KEY ({Columns(constraint.Columns)}) REFERENCES {OracleIdentifier.Qualify(to.Owner, to.Name)} ({Columns(constraint.ReferencedColumns)})");
                if (constraint.DeleteRule is "CASCADE" or "SET NULL")
                {
                    sql.Append($" ON DELETE {constraint.DeleteRule}");
                }

                break;
            default:
                throw new ArgumentException($"No DDL for constraint type {constraint.Type}.", nameof(constraint));
        }

        if (constraint.Deferrable)
        {
            sql.Append(constraint.InitiallyDeferred ? " DEFERRABLE INITIALLY DEFERRED" : " DEFERRABLE");
        }

        if (usingIndex is not null)
        {
            sql.Append($" USING INDEX ({usingIndex})");
        }

        if (!constraint.Enabled)
        {
            sql.Append(constraint.Validated ? " DISABLE VALIDATE" : " DISABLE");
        }
        else if (!constraint.Validated)
        {
            sql.Append(" ENABLE NOVALIDATE");
        }

        return sql.ToString();
    }

    /// <summary><c>CREATE [UNIQUE |BITMAP ]INDEX "O"."N" ON "O"."T" (…)</c>; null for index types it cannot write (domain, cluster …).</summary>
    public static string? CreateIndex(IndexInfo index, string name, string owner, string table)
    {
        var bitmap = index.IndexType.Contains("BITMAP", StringComparison.Ordinal);
        if (!bitmap && !index.IndexType.Contains("NORMAL", StringComparison.Ordinal))
        {
            return null;
        }

        var kind = bitmap ? "BITMAP " : index.Unique ? "UNIQUE " : "";
        var sql = new StringBuilder($"CREATE {kind}INDEX {OracleIdentifier.Qualify(owner, name)} ON {OracleIdentifier.Qualify(owner, table)} ({IndexColumns(index.Columns)})");
        if (index.IndexType.EndsWith("/REV", StringComparison.Ordinal))
        {
            sql.Append(" REVERSE");
        }

        if (!index.Visible)
        {
            sql.Append(" INVISIBLE");
        }

        return sql.ToString();
    }

    public static string IndexColumns(IEnumerable<IndexColumn> columns) =>
        string.Join(", ", columns.Select(c => (c.IsExpression ? c.Name : Q(c.Name)) + (c.Descending ? " DESC" : "")));

    public static string Columns(IEnumerable<string> names) => string.Join(", ", names.Select(Q));

    /// <summary>A string literal for COMMENT ON.</summary>
    public static string Literal(string? text) => $"'{(text ?? "").Replace("'", "''", StringComparison.Ordinal)}'";

    /// <summary>Comments every line (hints the user decides about; a script runner must never execute them).</summary>
    public static string Commented(string sql) =>
        string.Join("\n", sql.Split('\n').Select(line => line.StartsWith("--", StringComparison.Ordinal) ? line : "-- " + line));

    public static string ObjectKeyword(TableKind kind) => kind switch
    {
        TableKind.View => "VIEW",
        TableKind.MaterializedView => "MATERIALIZED VIEW",
        _ => "TABLE",
    };

    /// <summary>The object kind inside a sentence of the DDL proposal ("table").</summary>
    public static string ObjectWord(TableKind kind) => kind switch
    {
        TableKind.View => CompareText.ObjectView,
        TableKind.MaterializedView => CompareText.ObjectMaterializedView,
        _ => CompareText.ObjectTable,
    };

    /// <summary>The object kind at the start of <see cref="CompareText.RenameWarning"/> ("Table").</summary>
    public static string RenameSubject(TableKind kind) => kind switch
    {
        TableKind.View => CompareText.RenameSubjectView,
        TableKind.MaterializedView => CompareText.RenameSubjectMaterializedView,
        _ => CompareText.RenameSubjectTable,
    };

}
